### ISSUE TITLE
Pair to Pair Code Review

### ISSUE THREAD

**Issue by zemola** [Mithi-code/AwesomeBook#6]
Dear @Mithi-code , @roshan-bajgain.

Your project is working properly and all requirement was met, however, I have an optional suggestion.

Kindly increase your text fields in the add book section, I think it will look nicer that way.

![image](https://user-images.githubusercontent.com/59098116/143543239-36de6507-d825-4868-ada3-7b88b500fd39.png)

Happy coding

**Comment by Mithi-code** [comment]
Thanks for your feedback
close #6
